"""all tables

Revision ID: ad0980e45cae
Revises: 2b08a9f07284
Create Date: 2020-05-31 14:29:44.656046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0980e45cae'
down_revision = '2b08a9f07284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('przedmiot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=120), nullable=True),
    sa.Column('ects', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_przedmiot_ects'), 'przedmiot', ['ects'], unique=False)
    op.create_index(op.f('ix_przedmiot_nazwa'), 'przedmiot', ['nazwa'], unique=True)
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr', sa.String(length=64), nullable=True),
    sa.Column('miejsca', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sala_miejsca'), 'sala', ['miejsca'], unique=False)
    op.create_index(op.f('ix_sala_nr'), 'sala', ['nr'], unique=True)
    op.create_table('tytul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytulnauk', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tytul_tytulnauk'), 'tytul', ['tytulnauk'], unique=True)
    op.create_table('prowadzacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=64), nullable=True),
    sa.Column('nazwisko', sa.String(length=64), nullable=True),
    sa.Column('tytul_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tytul_id'], ['tytul.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prowadzacy_imie'), 'prowadzacy', ['imie'], unique=False)
    op.create_index(op.f('ix_prowadzacy_nazwisko'), 'prowadzacy', ['nazwisko'], unique=False)
    op.create_table('zajecie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dzien', sa.String(length=64), nullable=True),
    sa.Column('godzina', sa.String(length=32), nullable=True),
    sa.Column('prowadzacy_id', sa.Integer(), nullable=True),
    sa.Column('przedmiot_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prowadzacy_id'], ['prowadzacy.id'], ),
    sa.ForeignKeyConstraint(['przedmiot_id'], ['przedmiot.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_table('zajecie')
    op.drop_index(op.f('ix_prowadzacy_nazwisko'), table_name='prowadzacy')
    op.drop_index(op.f('ix_prowadzacy_imie'), table_name='prowadzacy')
    op.drop_table('prowadzacy')
    op.drop_index(op.f('ix_tytul_tytulnauk'), table_name='tytul')
    op.drop_table('tytul')
    op.drop_index(op.f('ix_sala_nr'), table_name='sala')
    op.drop_index(op.f('ix_sala_miejsca'), table_name='sala')
    op.drop_table('sala')
    op.drop_index(op.f('ix_przedmiot_nazwa'), table_name='przedmiot')
    op.drop_index(op.f('ix_przedmiot_ects'), table_name='przedmiot')
    op.drop_table('przedmiot')
    # ### end Alembic commands ###
